apiVersion: v2
appVersion: 7.2411.0
dependencies:
- alias: nginx
  condition: nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.7.2
- condition: gitea.enabled
  name: gitea
  repository: https://dl.gitea.io/charts
  version: 7.0.4
- alias: maria
  condition: maria.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.5.1
description: A Helm chart for installing nevisAdmin4.
#kubeVersion: '>= 1.27.0 <= v1.31.4-eks-2d5f260'
name: nevisadmin4
type: application
version: 7.2411.0
