apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - ap-southeast-1b
      - key: topology.k8s.aws/zone-id
        values:
          - apse1-az2
      - key: topology.kubernetes.io/region
        values:
          - ap-southeast-1
      - key: topology.kubernetes.io/zone
        values:
          - ap-southeast-1b