apiVersion: v1
kind: PersistentVolume
metadata:
  name: standard-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0ebf89d3579c676de  # Replace with your EBS volume ID
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i-05f1b94ad175978f0