{{- if .Values.certManager.createCAIssuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
spec:
  ca:
    secretName: ca-root-secret
{{- end }}
