{{- if and .Values.gitea.enabled .Values.maria.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-dbschema-{{ now | date "20060102150405" }}
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
    {{- with .Values.gitea.job.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gitea.job.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  activeDeadlineSeconds: 300
  {{- if .Values.nevisAdmin4.database.job.cleanupEnabled }}
  ttlSecondsAfterFinished: {{ .Values.nevisAdmin4.database.job.ttlSecondsAfterFinished | default 1200 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.gitea.job.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nevisadmin4.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.gitea.job.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
        - name: schema-dir
          emptyDir: {}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.nevisAdmin4.podSecurityContext | nindent 8 }}
      {{- if .Values.image.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecretName }}
      {{- end }}
      containers:
        - name: gitea-dbschema
          securityContext:
            {{- toYaml .Values.nevisAdmin4.containerSecurityContext | nindent 12 }}
          image: {{ .Values.image.repository }}/{{ .Values.image.imagePrefix }}/nevis-base-flyway:7.2411.0
          imagePullPolicy: Always
          volumeMounts:
            - name: schema-dir
              mountPath: /var/opt/flyway/sql/mysql
          env:
            - name: NEVIS_DBSCHEMA_MIGRATE_MAXWAIT_SECONDS
              value: "180"
            - name: DB_DRIVER
              value: mysql
            - name: NEVIS_DBSCHEMA_URL
              value: {{ .Values.database.host }}:{{ .Values.database.port }}/gitea
            {{- if contains "mariadb.database.azure.com" .Values.database.host }}
            - name: NEVIS_DBSCHEMA_HOSTNAME
              value: {{ .Values.database.host }}
            {{- end }}
            - name: NEVIS_DBROOT_USER
              {{- if .Values.database.root.preparedCredentialSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.root.preparedCredentialSecret}}
                  key: username
              {{- else }}
              value: {{ include "nevisadmin4.dbRootUsername" . }}
              {{- end }}
            - name: NEVIS_DBROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.root.preparedCredentialSecret }}
                  name: {{ .Values.database.root.preparedCredentialSecret}}
                  key: password
                  {{- else }}
                  name: nevisadmin4-env
                  key: rootpw
                  {{- end }}
            - name: NEVIS_DBSCHEMA_USER
              value: {{ .Values.gitea.gitea.config.database.USER }}
            - name: NEVIS_DBSCHEMA_PASSWORD
              value: {{ .Values.gitea.gitea.config.database.PASSWD }}
            - name: NEVIS_DBUSER_USER
              value: {{ .Values.gitea.gitea.config.database.USER }}
            - name: NEVIS_DBUSER_PASSWORD
              value: {{ .Values.gitea.gitea.config.database.PASSWD }}
            {{- if .Values.nevisAdmin4.database.enableSSL }}
            - name: NEVIS_DBSCHEMA_USE_SSL
              value: {{ .Values.nevisAdmin4.database.enableSSL | quote }}
            {{- end }}
          command:
            - "nevis-dbschema"
            - "migrate"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nevisAdmin4.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nevisAdmin4.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nevisAdmin4.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
