{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{ if and .Values.nevisAdmin4.saml.enabled (not .Values.nevisAdmin4.saml.keySecret ) }}
apiVersion: v1
data:
  saml.key: {{ include "nevisadmin4.samlKey" . | quote }}
  saml.crt: {{ include "nevisadmin4.samlCertificate" . | quote }}
kind: Secret
metadata:
  name: nevisadmin4-saml
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
type: Opaque
{{ end }}
{{ end }}
