{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{- if not .Values.git.credentialSecret }}
apiVersion: v1
data:
  key: {{ include "nevisadmin4.gitPrivateKey" . | quote }}
  key.pub: {{ include "nevisadmin4.gitPublicKey" . | quote }}
  known_hosts: {{ include "nevisadmin4.gitKnownHosts" . | quote }}
  password: {{ include "nevisadmin4.gitPassword" . | b64enc | quote }}
  username:  {{ include "nevisadmin4.gitUsername" . | b64enc | quote }}
  passphrase: {{ .Values.git.passphrase | b64enc | quote }}
kind: Secret
metadata:
  name: nevisadmin4-git
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
type: Opaque
{{- end }}
{{ end }}
