{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{ if .Values.nevisAdmin4.ldap.enabled }}
apiVersion: v1
data:
  truststore.p12: {{ .Values.nevisAdmin4.ldap.truststore64 }}
  passhprase: {{ .Values.nevisAdmin4.ldap.truststorePassphrase | b64enc | quote }}
kind: Secret
metadata:
  name: nevisadmin4-ldap
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
type: Opaque
{{ end }}
{{ end }}
