{{ if not .Values.database.root.preparedCredentialSecret }}
{{- range (append .Values.additionalComponentNamespaces .Release.Namespace) }}
apiVersion: v1
kind: Secret
metadata:
  name: root-creds
  namespace: {{ . }}
  labels:
    {{- include "nevisadmin4.labels" $ | nindent 4 }}
stringData:
  username: {{ include "nevisadmin4.dbRootUsernameWithHost" $ | quote }}
  password: {{ include "nevisadmin4.dbPassword" $ | quote }}
type: Opaque
---
{{ end }}
{{ end }}
