{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{- if or (not .Values.nevisAdmin4.database.credentialSecret) (not .Values.database.root.preparedCredentialSecret ) }}

{{- $adminPassword := (randAlpha 16) | b64enc }}
{{- if .Values.nevisAdmin4.password}}
  {{- $adminPassword = .Values.nevisAdmin4.password | b64enc }}
{{- end }}

{{- $applicationUserPw := (randAlpha 16) | b64enc }}
{{- if .Values.nevisAdmin4.database.applicationUserPassword }}
  {{- $applicationUserPw = .Values.nevisAdmin4.database.applicationUserPassword | b64enc }}
{{- end }}

{{- $schemaUserPw := (randAlpha 16) | b64enc }}
{{- if .Values.nevisAdmin4.database.schemaUserPassword }}
  {{- $schemaUserPw = .Values.nevisAdmin4.database.schemaUserPassword | b64enc }}
{{- end }}

{{- if and .Values.nevisAdmin4.credentialSecret (not .Values.nevisAdmin4.password) }}
  {{- $adminSecret := (lookup "v1" "Secret" .Release.Namespace .Values.nevisAdmin4.credentialSecret) }}
  {{- if $adminSecret -}}
  {{- $adminPassword = index $adminSecret.data "password" }}
  {{- end -}}
{{- end -}}

{{- if and (not .Values.nevisAdmin4.credentialSecret) (not .Values.nevisAdmin4.password) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "nevisadmin4-env") }}
  {{- if $secret }}
    {{- $adminPassword = index $secret.data "adminpassword" }}
  {{- end -}}
{{- end -}}

{{- if not .Values.nevisAdmin4.database.applicationUserPassword }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "nevisadmin4-env") }}
  {{- if $secret }}
    {{- $applicationUserPw = index $secret.data "applicationuserpw" }}
  {{- end -}}
{{- end -}}

{{- if not .Values.nevisAdmin4.database.schemaUserPassword }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "nevisadmin4-env") }}
  {{- if $secret }}
    {{- $schemaUserPw = index $secret.data "schemauserpw" }}
  {{- end -}}
{{- end -}}


apiVersion: v1
data:
  adminpassword: {{ $adminPassword | quote }}
  applicationuserpw:  {{ $applicationUserPw | quote }}
  rootpw: {{ include "nevisadmin4.dbPassword" . | b64enc | quote }}
  schemauserpw:  {{ $schemaUserPw | quote }}
kind: Secret
metadata:
  name: nevisadmin4-env
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
type: Opaque
{{- end }}
{{ end }}
