{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{- if and .Values.nevisAdmin4.tls.enabled (not .Values.nevisAdmin4.tls.keystoreSecret) }}
apiVersion: v1
data:
  keystore.p12: {{ include "nevisadmin4.keystore" . | quote }}
  passhprase: {{ include "nevisadmin4.keystorePassphrase" . | quote }}
kind: Secret
metadata:
  name: nevisadmin4-tls
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
type: Opaque
{{ end }}
{{ end }}
