{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
  name: {{ include "nevisadmin4.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
