{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: nevisadmin4-dbschema-{{ now | date "20060102150405" }}
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
    {{- with .Values.nevisAdmin4.database.job.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.nevisAdmin4.database.job.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  activeDeadlineSeconds: 300
  {{- if .Values.nevisAdmin4.database.job.cleanupEnabled }}
  ttlSecondsAfterFinished: {{ .Values.nevisAdmin4.database.job.ttlSecondsAfterFinished | default 1200 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.nevisAdmin4.database.job.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nevisadmin4.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.nevisAdmin4.database.job.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.nevisAdmin4.podSecurityContext | nindent 8 }}
      {{- if .Values.image.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecretName }}
      {{- end }}
      containers:
        - name: nevisadmin4-dbschema
          securityContext:
            {{- toYaml .Values.nevisAdmin4.containerSecurityContext | nindent 12 }}
          image: {{ .Values.image.repository }}/{{ .Values.image.imagePrefix }}/nevisadmin4-dbschema:{{ .Values.nevisAdmin4.image.migrationTag | default .Chart.AppVersion }}
          imagePullPolicy: Always
          env:
            - name: NEVIS_DBSCHEMA_MIGRATE_MAXWAIT_SECONDS
              value: "180"
            - name: NEVIS_DBSCHEMA_URL
              value: {{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.nevisAdmin4.database.name }}
            {{- if contains "mariadb.database.azure.com" .Values.database.host }}
            - name: NEVIS_DBSCHEMA_HOSTNAME
              value: {{ .Values.database.host }}
            {{- end }}
            {{- if eq .Values.database.type "postgresql" }}
            - name: DB_DRIVER
              value: postgresql
            {{- end }}
            - name: NEVIS_DBROOT_USER
              {{- if .Values.database.root.preparedCredentialSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.root.preparedCredentialSecret}}
                  key: username
              {{- else }}
              value: {{ include "nevisadmin4.dbRootUsername" . }}
              {{- end }}
            - name: NEVIS_DBROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.root.preparedCredentialSecret }}
                  name: {{ .Values.database.root.preparedCredentialSecret}}
                  key: password
                  {{- else }}
                  name: nevisadmin4-env
                  key: rootpw
                  {{- end }}
            - name: NEVIS_DBSCHEMA_USER
              {{- if .Values.nevisAdmin4.database.credentialSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nevisAdmin4.database.credentialSecret }}
                  key: schemaUser
              {{- else }}
              value: {{ .Values.nevisAdmin4.database.schemaUser }}
              {{- end }}
            - name: NEVIS_DBSCHEMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.nevisAdmin4.database.credentialSecret }}
                  name: {{ .Values.nevisAdmin4.database.credentialSecret }}
                  key: schemaUserPassword
                  {{- else }}
                  name: nevisadmin4-env
                  key: schemauserpw
                  {{- end }}
            - name: NEVIS_DBUSER_USER
              {{- if .Values.nevisAdmin4.database.credentialSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nevisAdmin4.database.credentialSecret }}
                  key: applicationUser
              {{- else }}
              value: {{ .Values.nevisAdmin4.database.applicationUser }}
              {{- end }}
            - name: NEVIS_DBUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.nevisAdmin4.database.credentialSecret }}
                  name: {{ .Values.nevisAdmin4.database.credentialSecret }}
                  key: applicationUserPassword
                  {{- else }}
                  name: nevisadmin4-env
                  key: applicationuserpw
                  {{- end }}
            {{- if .Values.nevisAdmin4.database.enableSSL }}
            - name: NEVIS_DBSCHEMA_USE_SSL
              value: {{ .Values.nevisAdmin4.database.enableSSL | quote }}
            {{- end }}
          command:
            - "nevis-dbschema"
            - "migrate"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nevisAdmin4.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nevisAdmin4.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nevisAdmin4.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
