{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nevisadmin4.labels" . | nindent 4 }}
  name: {{ include "nevisoperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
