{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{- range (append .Values.additionalComponentNamespaces .Release.Namespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nevisadmin4-role
  labels:
    {{- include "nevisadmin4.labels" $ | nindent 4 }}
  namespace: {{ . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operator.nevis-security.ch
    resources:
      - gitcredentials
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.nevis-security.ch
    resources:
      - nevisingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - operator.nevis-security.ch
    resources:
      - nevisdatabases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.nevis-security.ch
    resources:
      - neviscomponents
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.nevis-security.ch
    resources:
      - neviskeystores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.nevis-security.ch
    resources:
      - nevistruststores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
---
{{ end }}
{{ end }}
