{{ if (list nil true "true" | has .Values.nevisAdmin4.enabled) }}
{{- range (append .Values.additionalComponentNamespaces .Release.Namespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nevisadmin4-rolebinding
  labels:
    {{- include "nevisadmin4.labels" $ | nindent 4 }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nevisadmin4-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nevisadmin4.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{ end }}
