{{- range $ns := (append .Values.additionalComponentNamespaces .Release.Namespace) }}
apiVersion: operator.nevis-security.ch/v1
kind: GitCredentials
metadata:
  name: git-credentials
  labels:
    {{- include "nevisadmin4.labels" $ | nindent 4 }}
  namespace: {{ . }}
spec:
  url: {{ index $.Values.git.repositoryUrlMap $ns | default $.Values.git.repositoryUrl }}
  knownHosts: |
    {{- include "nevisadmin4.gitKnownHosts" $ | b64dec | nindent 4 }}
  credentialsSecret:
    name: {{ $.Values.git.credentialSecret | default "nevisadmin4-git" }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
